site_name: "YAOZARRS ‼️"
site_description: "Yet another ome-zarr model."
site_url: "https://tlambert03.github.io/yaozarrs/"
repo_url: "https://github.com/tlambert03/yaozarrs"
repo_name: "tlambert03/yaozarrs"

# https://zensical.org/docs/customization/
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - toc.follow

  palette:
    - scheme: "default"
      primary: white
      toggle:
        icon: material/brightness-7
        name: "Switch to dark mode"
    - scheme: "slate"
      primary: black
      toggle:
        icon: material/brightness-4
        name: "Switch to light mode"

  font:
    text: "Inter"
    # code: "Fira Code"

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
      permalink_title: "Link to this section"
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          inventories:
            # - "https://docs.python.org/3/objects.inv"
            - "https://docs.pydantic.dev/latest/objects.inv"
          paths:
            - "src"
          options:
            docstring_style: "numpy"
            show_bases: false
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            heading_level: 3
            show_root_heading: false
            show_root_toc_entry: false
            members_order: "__all__"
            extensions:
              - griffe_fieldz:
                  strip_annotated: true

extra_css:
  - stylesheets/zensical.css
  - stylesheets/extra.css

extra_javascript:
  - javascripts/yaozarrs-animation.js
